### ISSUE TITLE
Invalid XMLSchema date

### ISSUE THREAD

**Issue by elad-shaked** [yago-naga/yago4#3]
In yago-wd-facts.nt there are statements such that the object is: `"0000"^^<http://www.w3.org/2001/XMLSchema#gYear>`

e.g grep output
```
yago-wd-facts.nt:3511416:<http://yago-knowledge.org/resource/Dong_Xian>	<http://schema.org/deathDate>	"0000"^^<http://www.w3.org/2001/XMLSchema#gYear>	.
yago-wd-facts.nt:4012715:<http://yago-knowledge.org/resource/Tryphon>	<http://schema.org/deathDate>	"0000"^^<http://www.w3.org/2001/XMLSchema#gYear>	.
yago-wd-facts.nt:4023877:<http://yago-knowledge.org/resource/Emperor_Ai_of_Han>	<http://schema.org/deathDate>	"0000"^^<http://www.w3.org/2001/XMLSchema#gYear>	.
yago-wd-facts.nt:4088637:<http://yago-knowledge.org/resource/Granius_Licinianus>	<http://schema.org/deathDate>	"0000"^^<http://www.w3.org/2001/XMLSchema#gYear>	.
yago-wd-facts.nt:18885804:<http://yago-knowledge.org/resource/Lucius_Arruntius_Camillus_Scribonianus>	<http://schema.org/birthDate>	"0000"^^<http://www.w3.org/2001/XMLSchema#gYear>	.
```

According to XMLSchema "0000" is not a valid `gYear`: https://www.w3.org/TR/xmlschema-2/#noYearZero

**Comment by Tpt** [comment]
Thank you for this bug report.

This problem roots in the XML schema specifications. Indeed XML schema 1.0 states that year 0 is not valid but XML schema 1.1 changed its mind and states that "0000"^^xsd:gYear should be used for year -1 BC [c.f. xsd:dateTime "value space" note in XML schema 1.1 part 2 specification](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#dateTime).
It is also what states the recent [XPath specifications](https://www.w3.org/TR/xpath-functions-31/) that are used for the SPARQL built in functions.

We have chosen here to follow the recent XML schema and XPath specifications. It also has the advantage to make computations easier (no need of special case of BC dates). So, I don't think we will change this. Sorry if it makes some data usage harder but we had to pick a side. The third option would have been to not introduce BC dates in YAGO, but I'm not sure it would have been better.

Side note: following XML schema specifications, all dates are using the Gregorian calendar.

**Comment by elad-shaked** [comment]
I understand. I encountered this when I was using RDF4J, since it uses `org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl::newXMLGregorianCalendar`.
I recently contributed some PRs to RDF4J and am willing to to so again. How do you suggest I approach this?

**Comment by Tpt** [comment]
It would be amazing to update rdf4j indeed. Thank you! Maybe by having a XMLSchema 1.1 vs 1.0 option.

After some investigation, [Xerces seems to have some support for this](https://github.com/apache/xerces2-j/blob/e5a239b96fd2cff6566a29e7a4a3a4a2bbf9b0d4/src/org/apache/xerces/impl/dv/xs/AbstractDateTimeDV.java#L419). I am not sure how to use it properly (I am not very familiar with Xerces). Jena seems to have [simply copy/pasted these classes](https://github.com/apache/jena/tree/bfce1741cb12f9cf544235d32fba6598bc7341b5/jena-core/src/main/java/org/apache/jena/ext/xerces/impl/dv/xs). But it's not a very nice way to go.

**Comment by elad-shaked** [comment]
I opened [this issue](https://github.com/eclipse/rdf4j/issues/2436) over at RDF4J's repo. Given the response I dont think this will be resolved (at least I was convinced)
