### ISSUE TITLE
.ntx file format? "<< >>" in tuples?

### ISSUE THREAD

**Issue by 24601** [yago-naga/yago4#4]
I am not familiar with the .ntx files generated, what format is this? I can't seem to use the regular .nt (N-Triples) tooling on it, either, nor can seem to find any such format documented in the N-Triples world...

**Comment by Tpt** [comment]
Hi! Thank you for being interested in Yago 4. The ".ntx" file is using the RDF* (RDF star) model that provides a nice reification syntax. It's a quite new thing that is currently implemented by [Jena](https://jena.apache.org/documentation/rdfstar/), [RDF4J](https://rdf4j.org/documentation/programming/rdfstar/), [Stardog](https://www.stardog.com/blog/property-graphs-meet-stardog/), [GraphDB](http://graphdb.ontotext.com/documentation/9.2/free/devhub/rdf-sparql-star.html), [N3.js](https://github.com/rdfjs/N3.js/) and [RDF.rb](http://rdf.greggkellogg.net/yard/file.rdf-README.html#rdf-rdfstar). I will make it more clear on the website.

**Comment by 24601** [comment]
Thank you so much, @Tpt ! That was very, very helpful and now seeing Google results for RDF* I'm keyed into this format, just searching for .ntx and "<<" RDF wasn't helping, but this is GREAT! Thank you so much, already integrating N3.js!
